functionsDirectory = "/Users/torehanssen/sample/net/netlify/functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/torehanssen/sample/net"
publishOrigin = "default"
functions = "/Users/torehanssen/sample/net/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]